module Xing
  module Cms
    module Controllers
      autoload :Admin::AdminController, 'xing/cms/controllers/admin/admin_controller'
      autoload :Admin::BlogPostsController, 'xing/cms/controllers/admin/blog_posts_controller'
      autoload :Admin::FroalaDocumentsController, 'xing/cms/controllers/admin/froala_documents_controller'
      autoload :Admin::FroalaImagesController, 'xing/cms/controllers/admin/froala_images_controller'
      autoload :Admin::MenuItemsController, 'xing/cms/controllers/admin/menu_items_controller'
      autoload :Admin::PagesController, 'xing/cms/controllers/admin/pages_controller'
      autoload :MenusController, 'xing/cms/controllers/menus_controller'
      autoload :PagesController, 'xing/cms/controllers/pages_controller'
      autoload :TopicsController, 'xing/cms/controllers/topics_controller'
    end
  end
end

require 'xing/cms/engine'
require 'xing/cms/controllers/admin/admin_controller'
require 'xing/cms/controllers/admin/blog_posts_controller'
require 'xing/cms/controllers/admin/froala_documents_controller'
require 'xing/cms/controllers/admin/froala_images_controller'
require 'xing/cms/controllers/admin/menu_items_controller'
require 'xing/cms/controllers/admin/pages_controller'
require 'xing/cms/controllers/menus_controller'
require 'xing/cms/controllers/pages_controller'
require 'xing/cms/controllers/topics_controller'
require 'xing/cms/mappers/content_block_mapper'
require 'xing/cms/mappers/menu_item_mapper'
require 'xing/cms/mappers/menu_mapper'
require 'xing/cms/mappers/page_mapper'
require 'xing/cms/models/page/homepage'
require 'xing/cms/models/page/one_column'
require 'xing/cms/models/page/two_column'
require 'xing/cms/models/content_block'
require 'xing/cms/models/document'
require 'xing/cms/models/image'
require 'xing/cms/models/menu'
require 'xing/cms/models/menu_item'
require 'xing/cms/models/page'
require 'xing/cms/models/page_content'
require 'xing/cms/serializers/admin/menu_item_serializer'
require 'xing/cms/serializers/admin/menu_serializer'
require 'xing/cms/serializers/admin/menus_serializer'
require 'xing/cms/serializers/admin/page_serializer'
require 'xing/cms/serializers/admin/pages_serializer'
require 'xing/cms/serializers/content_block_serializer'
require 'xing/cms/serializers/menu_list_serializer'
require 'xing/cms/serializers/menu_node_serializer'
require 'xing/cms/serializers/menu_serializer'
require 'xing/cms/serializers/page_serializer'
require 'xing/cms/uploaders/doc_uploader'
require 'xing/cms/uploaders/image_uploader'
require 'xing/cms/uploaders/system_uploader'
