module Xing
  module Cms
    module Controllers
      autoload :AdminController, 'xing/cms/controllers/admin/admin_controller'
      autoload :BlogPostsController, 'xing/cms/controllers/admin/blog_posts_controller'
      autoload :FroalaDocumentsController, 'xing/cms/controllers/admin/froala_documents_controller'
      autoload :FroalaImagesController, 'xing/cms/controllers/admin/froala_images_controller'
      autoload :MenuItemsController, 'xing/cms/controllers/admin/menu_items_controller'
      autoload :PagesController, 'xing/cms/controllers/admin/pages_controller'
      autoload :MenusController, 'xing/cms/controllers/menus_controller'
      autoload :PagesController, 'xing/cms/controllers/pages_controller'
      autoload :TopicsController, 'xing/cms/controllers/topics_controller'
    end
  end
end


require 'xing/cms/admin'
require 'xing/cms/mappers/content_block_mapper'
require 'xing/cms/mappers/menu_item_mapper'
require 'xing/cms/mappers/menu_mapper'
require 'xing/cms/mappers/page_mapper'
require 'xing/cms/models/page/homepage'
require 'xing/cms/models/page/one_column'
require 'xing/cms/models/page/two_column'
require 'xing/cms/models/content_block'
require 'xing/cms/models/document'
require 'xing/cms/models/image'
require 'xing/cms/models/menu'
require 'xing/cms/models/menu_item'
require 'xing/cms/models/page'
require 'xing/cms/models/page_content'
require 'xing/cms/serializers/admin/menu_item_serializer'
require 'xing/cms/serializers/admin/menu_serializer'
require 'xing/cms/serializers/admin/menus_serializer'
require 'xing/cms/serializers/admin/page_serializer'
require 'xing/cms/serializers/admin/pages_serializer'
require 'xing/cms/serializers/content_block_serializer'
require 'xing/cms/serializers/menu_list_serializer'
require 'xing/cms/serializers/menu_node_serializer'
require 'xing/cms/serializers/menu_serializer'
require 'xing/cms/serializers/page_serializer'
require 'xing/cms/uploaders/doc_uploader'
require 'xing/cms/uploaders/image_uploader'
require 'xing/cms/uploaders/system_uploader'
#require 'xing/cms/observers/sitemap_observer'
#require 'xing/cms/observers/page_snapshot_observer'
require 'xing/cms/sitemap'
